### ISSUE TITLE
feat: Support for healthceck of Docker image

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#158]
Have not been able to find a way as of yet to perform a health check against the Docker container.  The typical methods of curl or wget are not working.  Wondering if you would consider a healthcheck endpoint or add a script that can be executed to determine the container health.

**Comment by JosephKav** [comment]
Yeah, the `-slim` docker images don't have curl or wget and from what I've read, adding them will make the container significantly bigger. Wo we'd have to go the script route. I'll look into a script and healthcheck endpoint

**Comment by JosephKav** [comment]
(haven't committed any of this yet)
I've got a healthcheck binary written in Go. It takes a URL as an argument and fails if a GET request to that URL fails. I've also made `/API/v1/healthcheck` which simply returns an "Alive" 200. 

Can't really think of anything to check on that healthcheck as no external databases can be used and I don't know when that URL would work but the others wouldn't.

I'm gonna make this entirely optional (rather than enable it by default) as Kubernetes would use the same image and has its own liveness probe. The healthcheck would be something like
```bash
healthcheck:
  test: ["CMD" "/healthcheck", http://localhost:8080/api/v1/healthcheck || exit 1"
```

**Comment by samcro1967** [comment]
I think that is perfect.  Can help by giving an indicator to docker monitoring apps that even though the container is running the web page is not accessible and there may be an issue.  Can then use some automation to auto restart the container, send alerts, or both.

**Comment by JosephKav** [comment]
Added a `/healthcheck` binary to the Docker container
```yaml
healthcheck:
  test: ["CMD" "/healthcheck", "http://localhost:8080/api/v1/healthcheck"]
```

**Comment by JosephKav** [comment]
Perfect, thanks for letting me know it's working :)
