### ISSUE TITLE
Move services out of primary config file into a services folder

### ISSUE THREAD

**Issue by quantumzedno** [release-argus/Argus#85]
I'd like to request a feature where in instead of configuring all of the services as part of the primary config file, that the primary config file pull them from any .yml file in a given services folder.

I've been playing around with services all afternoon and got 3 working, after which I commented them all out in the config file in order to work on a 4th (logging was getting very busy) only to realize that the server overwrite / deleted all commented lines in the config file thus resulting in me needing to start from scratch on the 3 I had already got working. 

Having each service be it's own file would allow for easy enabling/disabling by renaming the files to a non .yml extension and would also just keep everything a lot more organized when you end up with dozens of monitored services (my goal is to use this to monitor all server based applications we host eventually which could end up being quite a lot)

**Comment by JosephKav** [comment]
I really don't see any benefit to doing this. I much prefer having it all in one file as it makes comparisons/copying easier and it'd mean potentially loads of tiny files. I'd much rather spend time looking into how I'd get commented out lines to be kept on save.
There's really no need to comment out services if it's just for testing as you can `-test.service`

**Comment by quantumzedno** [comment]
# It is split into several files forming the configuration hierarchy outlined
# below, all located in the /etc/apache2/ directory:
#
#       /etc/apache2/
#       |-- apache2.conf
#       |       `--  ports.conf
#       |-- mods-enabled
#       |       |-- *.load
#       |       `-- *.conf
#       |-- conf-enabled
#       |       `-- *.conf
#       `-- sites-enabled
#               `-- *.conf
#
#

**Comment by samcro1967** [comment]
I also would prefer all service configs in one file.  I use -test.service quite a lot when adding new services where I only want to test that service.  Maybe another option could be adding a service option called active (or something more creative) with a value of true or false so that it is only added to the dashboard and checks if true.  If not present, defaults to true.  That way it can be kept in the config file at all times and set to false.

Maybe a quick alternative to comments could be to just add it to the yaml config and do nothing with it.

```
  Argus:
    comment:  This is a test comment.
    type: github
    url: release-argus/argus
```

**Comment by JosephKav** [comment]
I agree with samcro. I just merged a change giving that `active: false` option to services. Thinking I'll do the `comment` suggestion as well since it'd not a lot of work and some people may like/want it.

Supporting multiple files would be a pain from a saving perspective as it'd have to keep track of where each service is stored and then go through the list of all services and check which others may be in that file. Then there's the issue of defaults/settings/notify/webhook which would have all have to be in the same file (each type) and then we'd need to store the location of those files. I'm just gonna keep it how it is with 1 file for the config for the time being

**Comment by samcro1967** [comment]
Tested both active and comment and both are working for me.  I was envisioning if a service was set as not active, it would also not display the card.  Not sure if that is an easy ask.  Or maybe a separate Boolean parameter called `visibile`?  Although not sure why one would want it active and then hidden from the dashboard.

**Comment by JosephKav** [comment]
> Tested both active and comment and both are working for me. I was envisioning if a service was set as not active, it would also not display the card. Not sure if that is an easy ask. Or maybe a separate Boolean parameter called `visibile`? Although not sure why one would want it active and then hidden from the dashboard.

Had a bit of a rethink on how to hide the `!active` services and got it working cleanly (imo). I've done a rebase and modified the original commit that added `active`. `active: false` should now hide the service completely from the web ui, but it'll still be visible in the config file after saves as well as at `Status/Configuration` in the web ui

**Comment by samcro1967** [comment]
Test latest commit and it has removed a test services from the dashboard.

**Comment by JosephKav** [comment]
> Test latest commit and it has removed a test services from the dashboard.

Config?

**Comment by samcro1967** [comment]
I guess my response was a little ambiguous.  it worked as expected.  It persisted in the config with active set to false, but is not displayed on the dashboard.
